version: 2

run:
  timeout: 3m
linters-settings:
  govet:
    enable-all: true
linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unconvert
    - unused
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - revive
